import { FC } from 'react'

type Props = {}

type PropTwo = {
  headline: string,
  body: string,
  className?: string
}

type PropThree = {
  className?: string
}

const Copy: FC<PropTwo> = ({ headline, body, className }) => {
  return (
    <div>
      <div className={"max-w-md " + className}>
        <div className={"reservoir-h1 mb-3 " + className}>
          {headline}
        </div>
        <div className="text-xl">
          {body}
        </div>
      </div>
    </div>
  )
}

const Module: FC<PropThree> = ({ className, children }) => {
  return (
    <div className={`flex p-4 max-w-[1300px] m-auto ${className} flex-col md:flex-row`}>
      {children}
    </div>
  )
}

const HomeContent: FC<Props> = () => {
  const featured = [
    'https://cdn.finiliar.com/sad_short_ghost/MTg1NgRx68.gif',
    'https://cdn.finiliar.com/neutral_short_dance/MTA2NwRx70.gif',
    'https://cdn.finiliar.com/sad_short_ghost/MTg1NgRx68.gif',
    'https://cdn.finiliar.com/sad_short_ghost/MTg1NgRx68.gif',
    'https://cdn.finiliar.com/sad_short_ghost/MTg1NgRx68.gif',
    'https://cdn.finiliar.com/sad_short_ghost/MTg1NgRx68.gif',
    'https://cdn.finiliar.com/sad_short_ghost/MTg1NgRx68.gif',
    'https://cdn.finiliar.com/sad_short_ghost/MTg1NgRx68.gif',
    'https://cdn.finiliar.com/sad_short_ghost/MTg1NgRx68.gif',
    'https://cdn.finiliar.com/sad_short_ghost/MTg1NgRx68.gif',
    'https://cdn.finiliar.com/sad_short_ghost/MTg1NgRx68.gif'
  ]
  return (
    <div className="pb-11 mb-11 overflow-x-hidden w-[100vw]">
      <Module className="justify-center text-center mt-4 m-auto">
        <Copy className="text-[#FF4F4F]" headline='Meet the finiliar' body='The finiliar are digital companions that keep you up to date with the things you care about.' />
      </Module>
      <div className="flex ml-[-50px] mt-[100px] overflow-hidden">
        {featured.map(item => {
          return (
            <div key={item}>
              <img src={item} alt="Example fini" className="rounded-xl max-w-[200px] mx-2" />
            </div>
          )
        })}
      </div>
      <div className="md:hidden flex ml-[-100px] mt-[20px] overflow-hidden">
        {featured.map((item, index) => {
          if (index < 5) return null
          return (
            <div key={item}>
              <img src={item} alt="Example fini" className="rounded-xl max-w-[200px] mx-2" />
            </div>
          )
        })}
      </div>
      <div className="mt-[200px] left-0">
        <Module className="mt-[100px] z-9 justify-around">
          <Copy className="text-[#7D7EF3]" headline='A recent discovery' body='The crypto market of 2021 gave rise to a new wave of finiliar that embody various crypto coins. Feeding on the data generated by these coins, the finiliar rejoice when prices are up and sob when they go down. You can own these finiliar as NFTs.' />
          <img
            className="max-w-[400px] w-full my-10 md:my-0 md:ml-16 rounded-[17px]" 
            src="https://cdn.finiliar.com/sad_short_ghost/MTg1NgRx68.gif" alt="Example fini" />
        </Module>
        <img
          src="/graph.svg"
          className="z-[-1] absolute w-[100vw] left-0 right-0 mt-[-400px] min-w-[800px]" alt="Graph background"
        />
      </div>
      <div className="md:pt-[75px] left-0 bg-[#edf7e8]">
        <div
          style={{ background: 'linear-gradient(180deg, #edf7e8 0%, #edf7e8 70%, #edf7e800 100%)' }}
          className="max-w-[100vw] h-[1400px] md:h-[1000px] absolute z-[-1] left-0 right-0 md:mt-[-60px] mt-[-200px]" />
        <Module className="pt-[200px] z-9 justify-around">
          <img
            className="max-w-[600px] mb-[25px] md:mr-[50px] md:w-[50%]" 
            src="/island.png" alt="Fini island" />
          <Copy className="text-[#A17235]" headline='Origins' body='The first finiliar were discovered in 2016 by a researcher named Ed Fornieles. Strange code turned out to be a new, adorable species of being. Ed has presented his research around the world as videos and sculptures.' />
        </Module>
      </div>
      <div className="mt-[300px] left-0 mb-[100px]">
        <Module className="mt-[200px] z-9 justify-around">
          <Copy className="text-[#B980A5]" headline='Coming soon' body='Use your iPhone and Apple Watch to save your friends to track your crypto portfolio.' />
          <img
            className="max-w-[300px] mt-[50px] md:mr-[50px] md:w-[50%]" 
            src="/watch.png" alt="Fini watch app" />
        </Module>
      </div>
    </div>
  )
}

export default HomeContent
